name: eews
description: EEWS Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # Background tasks - ONLY ONE OF THESE:
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Networking
  http: ^1.6.0
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  
  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Location
  geolocator: ^14.0.2
  
  # Background Service
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true